[book]
title = "Руководство по ремонту Renault Symbol"
authors = ["mi"]
language = "ru"
src = "src"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/mi/reno-symbol.ru"
default-theme = "light"
preferred-dark-theme = "ayu"

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 15
use-boolean-and = true

[output.html.playground]
runnable = false

[output.pdf]
chrome = "chromium"
no-sandbox = true

[preprocessor]
